#!/bin/bash

script_path=./infrastructure/buildout/bin
script=test

pushd $script_path
if [ -f $script ]
then
    ./$script
else
    echo "The script does not exist. Could not find: $script_path/$script"
fi
popd
