#!/bin/bash

# This script is intended to be executed from a launcher or desktop icon. 
# It sets some environment variables, check if there is a local python 
# interpreter available and and launches a new terminal.
# You should pass the project root as the first parameter of this script.

export BIMAKER_TITLE=BibtexIndexMaker
export BIMAKER_HOME=$1
export PATH=$BIMAKER_HOME/public/bin:$PATH
export PYLINTRC=$BIMAKER_HOME/infrastructure/buildout/.pylintrc

if ! test -e $BIMAKER_HOME/public/bin/python
then
    pushd $BIMAKER_HOME/infrastructure/environment
    echo $PWD
    ./setup-devenv
    popd
fi

gnome-terminal --working-directory=$BIMAKER_HOME --title=$BIMAKER_TITLE
exit
