#!/bin/bash

# This script is intended to be executed from a launcher or desktop icon. 
# It sets some environment variables, check if there is a local python 
# interpreter available and and launches a new terminal.
# You should pass the project root as the first parameter of this script.

export BIBIM_TITLE=BibtexIndexMaker
export BIBIM_HOME=$1
export PATH=$BIBIM_HOME/public/bin:$PATH
export PYLINTRC=$BIBIM_HOME/infrastructure/buildout/.pylintrc

if ! test -e $BIBIM_HOME/public/bin/python
then
    pushd $BIBIM_HOME/infrastructure/environment
    echo $PWD
    ./setup-devenv
    popd
fi

gnome-terminal --working-directory=$BIBIM_HOME --title=$BIBIM_TITLE
exit
