# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_reference_editor.ui'
#
# Created: Sun May  9 20:16:07 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ReferenceEditor(object):
    def setupUi(self, ReferenceEditor):
        ReferenceEditor.setObjectName("ReferenceEditor")
        ReferenceEditor.resize(842, 713)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReferenceEditor.sizePolicy().hasHeightForWidth())
        ReferenceEditor.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(ReferenceEditor)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, -1, -1, 9)
        self.formLayout.setObjectName("formLayout")
        self.resultLabel = QtGui.QLabel(ReferenceEditor)
        self.resultLabel.setObjectName("resultLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.resultLabel)
        self.resultLine = QtGui.QLineEdit(ReferenceEditor)
        self.resultLine.setObjectName("resultLine")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.resultLine)
        self.queryLabel = QtGui.QLabel(ReferenceEditor)
        self.queryLabel.setObjectName("queryLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.queryLabel)
        self.queryLine = QtGui.QLineEdit(ReferenceEditor)
        self.queryLine.setObjectName("queryLine")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.queryLine)
        self.validityLabel = QtGui.QLabel(ReferenceEditor)
        self.validityLabel.setObjectName("validityLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.validityLabel)
        self.validitySpin = QtGui.QDoubleSpinBox(ReferenceEditor)
        self.validitySpin.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.validitySpin.setPrefix("")
        self.validitySpin.setMaximum(1.0)
        self.validitySpin.setSingleStep(0.05)
        self.validitySpin.setObjectName("validitySpin")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.validitySpin)
        self.filePathLabel = QtGui.QLabel(ReferenceEditor)
        self.filePathLabel.setObjectName("filePathLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.filePathLabel)
        self.filePathLine = QtGui.QLineEdit(ReferenceEditor)
        self.filePathLine.setObjectName("filePathLine")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.filePathLine)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtGui.QFrame(ReferenceEditor)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tablesHorizontalLayout = QtGui.QHBoxLayout()
        self.tablesHorizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.tablesHorizontalLayout.setObjectName("tablesHorizontalLayout")
        self.fieldsLayout = QtGui.QVBoxLayout()
        self.fieldsLayout.setObjectName("fieldsLayout")
        self.fieldsLabel = QtGui.QLabel(ReferenceEditor)
        self.fieldsLabel.setObjectName("fieldsLabel")
        self.fieldsLayout.addWidget(self.fieldsLabel)
        self.fields = QtGui.QTreeWidget(ReferenceEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fields.sizePolicy().hasHeightForWidth())
        self.fields.setSizePolicy(sizePolicy)
        self.fields.setMinimumSize(QtCore.QSize(100, 0))
        self.fields.setIndentation(0)
        self.fields.setObjectName("fields")
        self.fieldsLayout.addWidget(self.fields)
        self.tablesHorizontalLayout.addLayout(self.fieldsLayout)
        self.multiVerticalLayout = QtGui.QVBoxLayout()
        self.multiVerticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.multiVerticalLayout.setObjectName("multiVerticalLayout")
        self.authorsLayout = QtGui.QVBoxLayout()
        self.authorsLayout.setContentsMargins(-1, -1, -1, 9)
        self.authorsLayout.setObjectName("authorsLayout")
        self.authorsLabel = QtGui.QLabel(ReferenceEditor)
        self.authorsLabel.setObjectName("authorsLabel")
        self.authorsLayout.addWidget(self.authorsLabel)
        self.authors = QtGui.QTreeWidget(ReferenceEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authors.sizePolicy().hasHeightForWidth())
        self.authors.setSizePolicy(sizePolicy)
        self.authors.setMinimumSize(QtCore.QSize(100, 0))
        self.authors.setIndentation(0)
        self.authors.setObjectName("authors")
        self.authorsLayout.addWidget(self.authors)
        self.multiVerticalLayout.addLayout(self.authorsLayout)
        self.editorsLayout = QtGui.QVBoxLayout()
        self.editorsLayout.setContentsMargins(-1, -1, -1, 0)
        self.editorsLayout.setObjectName("editorsLayout")
        self.editorsLabel = QtGui.QLabel(ReferenceEditor)
        self.editorsLabel.setObjectName("editorsLabel")
        self.editorsLayout.addWidget(self.editorsLabel)
        self.editors = QtGui.QTreeWidget(ReferenceEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editors.sizePolicy().hasHeightForWidth())
        self.editors.setSizePolicy(sizePolicy)
        self.editors.setMinimumSize(QtCore.QSize(100, 0))
        self.editors.setIndentation(0)
        self.editors.setObjectName("editors")
        self.editorsLayout.addWidget(self.editors)
        self.multiVerticalLayout.addLayout(self.editorsLayout)
        self.tablesHorizontalLayout.addLayout(self.multiVerticalLayout)
        self.verticalLayout.addLayout(self.tablesHorizontalLayout)

        self.retranslateUi(ReferenceEditor)
        QtCore.QMetaObject.connectSlotsByName(ReferenceEditor)

    def retranslateUi(self, ReferenceEditor):
        ReferenceEditor.setWindowTitle(QtGui.QApplication.translate("ReferenceEditor", "ReferenceEditor", None, QtGui.QApplication.UnicodeUTF8))
        self.resultLabel.setText(QtGui.QApplication.translate("ReferenceEditor", "Extracted from", None, QtGui.QApplication.UnicodeUTF8))
        self.queryLabel.setText(QtGui.QApplication.translate("ReferenceEditor", "Using query", None, QtGui.QApplication.UnicodeUTF8))
        self.validityLabel.setText(QtGui.QApplication.translate("ReferenceEditor", "Validity", None, QtGui.QApplication.UnicodeUTF8))
        self.filePathLabel.setText(QtGui.QApplication.translate("ReferenceEditor", "File path", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsLabel.setText(QtGui.QApplication.translate("ReferenceEditor", "Fields:", None, QtGui.QApplication.UnicodeUTF8))
        self.fields.headerItem().setText(0, QtGui.QApplication.translate("ReferenceEditor", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.fields.headerItem().setText(1, QtGui.QApplication.translate("ReferenceEditor", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.fields.headerItem().setText(2, QtGui.QApplication.translate("ReferenceEditor", "Valid", None, QtGui.QApplication.UnicodeUTF8))
        self.authorsLabel.setText(QtGui.QApplication.translate("ReferenceEditor", "Authors:", None, QtGui.QApplication.UnicodeUTF8))
        self.authors.headerItem().setText(0, QtGui.QApplication.translate("ReferenceEditor", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.authors.headerItem().setText(1, QtGui.QApplication.translate("ReferenceEditor", "Middle Name", None, QtGui.QApplication.UnicodeUTF8))
        self.authors.headerItem().setText(2, QtGui.QApplication.translate("ReferenceEditor", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.editorsLabel.setText(QtGui.QApplication.translate("ReferenceEditor", "Editors:", None, QtGui.QApplication.UnicodeUTF8))
        self.editors.headerItem().setText(0, QtGui.QApplication.translate("ReferenceEditor", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.editors.headerItem().setText(1, QtGui.QApplication.translate("ReferenceEditor", "Middle Name", None, QtGui.QApplication.UnicodeUTF8))
        self.editors.headerItem().setText(2, QtGui.QApplication.translate("ReferenceEditor", "Last Name", None, QtGui.QApplication.UnicodeUTF8))

